export type PdfLang = 'id' | 'en'

export const pdfLabels: Record<PdfLang, Record<string, string>> = {
  id: {
    phone: 'Telp',
    tax: 'NPWP/NIB',
    orderLabel: 'Dokumen Pesanan',
    orderTitle: 'SURAT PESANAN',
    billTo: 'Pelanggan',
    item: 'Item',
    qty: 'Qty',
    price: 'Harga',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Diskon',
    notes: 'Catatan',
    serviceTitle: 'SERVICE ORDER',
    device: 'Perangkat',
    problem: 'Kerusakan',
    serviceDetails: 'Detail Servis',
    itemsServices: 'Item / Jasa',
    itemsTotal: 'Total Item',
    description: 'Deskripsi',
    cost: 'Biaya',
    totalCost: 'Total Biaya',
    paid: 'Dibayar',
    remainingBalance: 'Sisa Tagihan',
    paymentHistory: 'Riwayat Pembayaran',
    date: 'Tanggal',
    method: 'Metode',
    amount: 'Nominal',
    warrantyExpired: 'GARANSI KADALUARSA',
    warrantyActive: 'GARANSI AKTIF',
    validUntil: 'Berlaku sampai',
    cashier: 'Kasir',
    customerShort: 'Pel',
    paidShort: 'Bayar',
    shortageDp: 'Kurang (DP)',
    change: 'Kembali',
    paymentTitle: 'BUKTI PEMBAYARAN',
    invoiceNo: 'No Invoice',
    invoiceTotal: 'Total Invoice',
    status: 'Status',
    footerFallback: 'Terima kasih atas kepercayaan Anda.',
  },
  en: {
    phone: 'Phone',
    tax: 'NPWP/NIB',
    orderLabel: 'Order Document',
    orderTitle: 'SALES ORDER',
    billTo: 'Customer',
    item: 'Item',
    qty: 'Qty',
    price: 'Price',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Discount',
    notes: 'Notes',
    serviceTitle: 'SERVICE ORDER',
    device: 'Device',
    problem: 'Problem',
    serviceDetails: 'Service Details',
    itemsServices: 'Items / Services',
    itemsTotal: 'Items Total',
    description: 'Description',
    cost: 'Cost',
    totalCost: 'Total Cost',
    paid: 'Paid',
    remainingBalance: 'Outstanding Balance',
    paymentHistory: 'Payment History',
    date: 'Date',
    method: 'Method',
    amount: 'Amount',
    warrantyExpired: 'WARRANTY EXPIRED',
    warrantyActive: 'WARRANTY ACTIVE',
    validUntil: 'Valid until',
    cashier: 'Cashier',
    customerShort: 'Cust',
    paidShort: 'Paid',
    shortageDp: 'Due (DP)',
    change: 'Change',
    paymentTitle: 'PAYMENT RECEIPT',
    invoiceNo: 'Invoice No.',
    invoiceTotal: 'Invoice Total',
    status: 'Status',
    footerFallback: 'Thank you for your trust.',
  },
}
