export const appLabels = {
  dashboard: 'Dasbor',
  home: 'Beranda',
  pos: 'POS',
  products: 'Produk',
  customers: 'Pelanggan',
  salesOrders: 'Pesanan Penjualan',
  orders: 'Pesanan',
  payments: 'Pembayaran',
  inventory: 'Stok & Gudang',
  cashBank: 'Kas & Bank',
  reports: 'Laporan',
  more: 'Lainnya',
  offlineSync: 'Sinkron Offline',
  companySetting: 'Pengaturan Usaha',
  active: 'Aktif',
  inactive: 'Nonaktif',
  paid: 'Lunas',
  partial: 'Sebagian',
  unpaid: 'Belum Bayar',
  pending: 'Pending',
  failed: 'Gagal',
  refunded: 'Refund',
} as const
